version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "rust"]

  - package-ecosystem: "npm"
    directory: "/web/musician"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["dependencies", "npm"]

  - package-ecosystem: "npm"
    directory: "/web/engineer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["dependencies", "npm"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
