#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == remove ]]; then systemctl stop openiem-server.service >/dev/null 2>&1 || true; systemctl disable openiem-server.service >/dev/null 2>&1 || true; fi
exit 0
